# Maximum number of blocks that can be mined in a single vein
max-vein-size: 16

# List of ore types that can be vein mined
ores:
  - COAL_ORE
  - IRON_ORE
  - GOLD_ORE
  - DIAMOND_ORE
  - REDSTONE_ORE
  - LAPIS_ORE
  - EMERALD_ORE
  - NETHER_QUARTZ_ORE
  - NETHER_GOLD_ORE
  - ANCIENT_DEBRIS
  - COPPER_ORE
  - DEEPSLATE_COAL_ORE
  - DEEPSLATE_IRON_ORE
  - DEEPSLATE_GOLD_ORE
  - DEEPSLATE_DIAMOND_ORE
  - DEEPSLATE_REDSTONE_ORE
  - DEEPSLATE_LAPIS_ORE
  - DEEPSLATE_EMERALD_ORE
  - DEEPSLATE_COPPER_ORE